interface Window {
  env?: {
    [key: string]: any;
    fineractPlatformTenantId?: string;
    fineractPlatformTenantIds?: string;
    fineractApiUrls?: string;
    fineractApiUrl?: string;
    allow_switching_backend_instance?: boolean;
    allowServerSwitch?: string | boolean;
    apiProvider?: string;
    apiVersion?: string;
    apiActuator?: string;
    enableRememberMe?: string | boolean;
    oauthServerEnabled?: string | boolean;
    oauthServerUrl?: string;
    oauthServerLogoutUrl?: string;
    oauthAppId?: string;
    oauthClientId?: string;
    oauthProviderName?: string;
    oauthIssuerUrl?: string;
    oauthAuthorizeUrl?: string;
    oauthTokenUrl?: string;
    oauthRedirectUri?: string;
    oauthPostLogoutRedirectUri?: string;
    oauthScope?: string;
    defaultLanguage?: string;
    supportedLanguages?: string;
    preloadClients?: boolean;
    defaultCharDelimiter?: string;
    displayBackEndInfo?: string;
    displayTenantSelector?: string;
    tenantLogoUrl?: string;
    waitTimeForNotifications?: number;
    waitTimeForCOBCatchUp?: number;
    sessionIdleTimeout?: number;
    vNextApiUrl?: string;
    vNextApiProvider?: string;
    vNextApiVersion?: string;
    interbankTransfers?: boolean;
    minPasswordLength?: number;
    oidcServerEnabled?: string | boolean;
    oidcBaseUrl?: string;
    oidcClientId?: string;
    oidcApiUrl?: string;
    oidcFrontUrl?: string;
  };
}
