name: build-run

on:
  push:
    branches:
      - main
      - mnzl/*
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Run Lint and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: '22.9.0'
      - name: Angular CLI install
        run: npm install -g --silent @angular/cli@16.0.2

      - run: npm install

      - run: npx ng lint

      - run: npx stylelint "src/**/*.scss"

      - run: npx prettier . --check

      - run: npm run build:prod
